services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: excel_tools_backend
    volumes:
      - excel_temp_files:/app/temp_files
    environment:
      - DEBUG=false
      - CORS_ORIGINS=["https://shamim313.com","https://www.shamim313.com"]
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - excel_network
      - shamim_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: excel_tools_front
    environment:
      - NEXT_PUBLIC_API_URL=https://shamim313.com/api
      - BACKEND_URL=https://shamim313.com/api
    depends_on:
      - backend
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      # Nginx Proxy Manager labels
      - "com.nginx-proxy-manager.enabled=true"
      - "com.nginx-proxy-manager.host=shamim313.com"
      - "com.nginx-proxy-manager.port=3000"
    networks:
      - excel_network
      - shamim_network

volumes:
  excel_temp_files:
    driver: local

networks:
  excel_network:
    driver: bridge
  shamim_network:
    external: true
