services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: excel_tools_backend
    env_file: .env
    volumes:
      - excel_temp_files:/app/temp_files
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - excel_network
      - shamim_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: excel_tools_front
    env_file: .env
    depends_on:
      - backend
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - excel_network
      - shamim_network

volumes:
  excel_temp_files:
    driver: local

networks:
  excel_network:
    driver: bridge
  shamim_network:
    external: true
